import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClearStorageDependOnTabs from "@/lib/contexts/clearStorageDependOnTabs";
import dynamic from "next/dynamic";
import TopLayout from "@/components/layout/topLayout";
import { ThemeProvider } from "@/lib/contexts/ThemeContext";
import { KEY_USER_PROFILE } from "@/lib/config";

const UserRoleContextProvider = dynamic(() => import("@/lib/contexts/userRoleContext"), { ssr: false })

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClearStorageDependOnTabs keys={[KEY_USER_PROFILE]}>
          <UserRoleContextProvider>
              <ThemeProvider>
                <TopLayout>{children}</TopLayout>
              </ThemeProvider>
            </UserRoleContextProvider>
        </ClearStorageDependOnTabs>
      </body>
    </html>
  );
}


